baseURL = "https://til.hal.com.mx/"
languageCode = "es-MX"
title = "HAL Today I Learned"
theme="twentynineteen"
publishdir="docs"

[params]
    accent_color = "#FF0000"

[menu]
    [[menu.social]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/HAL-DEV/hal-til-blog"
