baseURL = "https://til.hal.com.mx/"
languageCode = "es-mx"
title = "HAL Today I Learned"
theme="twentynineteen-hal"
publishdir="docs"
googleAnalytics = "G-BZM6JQ4ZWC"

[params]
    accent_color = "#EE0000"
    body_font = "Source Sans Pro"
    using_google_fonts = 1
    code_theme = "shades-of-purple"

[menu]
    [[menu.social]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/HAL-DEV/hal-til-blog"

