baseURL = "https://hal-dev.github.io/hal-til-blog/"
languageCode = "es-mx"
title = "HAL Today I Learned"
theme="twentynineteen-hal"
publishdir="docs"
googleAnalytics = "G-BZM6JQ4ZWC"
disqusShortname = "today-i-learned-hal"
RelativeURLs=true
CanonifyURLs=true

[params]
    accent_color = "#EE0000"
    body_font = "Source Sans Pro"
    using_google_fonts = 1
    code_theme = "night-owl"

[menu]
    [[menu.social]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/HAL-DEV/hal-til-blog"
